main=presentation

all:
	pdflatex --shell-escape $(main).tex
	pdflatex --shell-escape $(main).tex

clean:
	rm -f $(main).pdf *.log *.aux *.bbl *.blg *.out *.toc *~ *.nav *.snm *.vrb *.fls *.synctex.gz *.fdb\_latexmk
